spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: public
      config:
        server-addr: 127.0.0.1:8848
        namespace: public
        group: DEFAULT_GROUP
        file-extension: yaml
        import-check:
          enabled: false
        ext-config[0]:  #额外的配置文件
          data-id: new-test-dev.yaml
          group: TEST_GROUP #所在组 不填则默认
          refresh: true  #是否支持动态刷新
#        ext-config[1]:
#          data-id: nacos-demo.yaml
#        ext-config[2]:
#          data-id: application.yaml  #将相关配置内容放到 nacos 服务器上，读取就行
#          group: TEST_GROUP
#          refresh: true

#配置加载的优先级-命名冲突
# 1 基础的和扩展的存在命名冲突 - 以基础的为准
# 2 扩展的之间存在命名冲突 - ext-config[n] n的值越大优先级越高
